Update --skip-error

diff --git a/opensearch b/opensearch
--- a/opensearch
+++ b/opensearch
@@ -24,10 +24,10 @@
 ##
 ## ------ Text ------
 ## Usage:
-##   opensearch [OPTION]... [SUB_COMMAND]
+##   opensearch [OPTION]... [COMMAND]
 ##
 ## Options:
-##   -c,     --config-directory DIRECTORY
+##   -c,     --config-directory DIRECTORY 
 ##                               設定ファイルのディレクトリを指定する
 ##   -h,     --help              このヘルプを表示して終了する
 ##   -v,     --version           バージョン情報を表示して終了する
@@ -35,6 +35,7 @@
 ## Commands:
 ##   add       OpenSearch description document を追加する
 ##   contact   OpenSearch description document の作成者に連絡する
+##   list      OpenSearch description document の一覧を表示する
 ##   search    OpenSearch description document を元に検索を行う
 ##   show      OpenSearch description document を表示する
 ##   update    OpenSearch description document を更新する
@@ -347,6 +348,7 @@ parser_definition_contact() {
 		'' 'Options:'
 
 	option extarnal       -e --{no-}extarnal init:@no on: no:echo var:COMMAND -- '外部プログラムを起動する'
+	flag   skipFlag       -s --skip-error    init:@no -- 'エラーをスキップして次のファイルを処理する'
 	disp   :usage_contact -h --help          -- 'このヘルプを表示して終了する'
 }
 
@@ -371,6 +373,7 @@ parser_definition_search() {
 	option extarnal      -e --{no-}extarnal      init:@no on: no:echo var:COMMAND -- '外部プログラムを起動する'
 	param  :'add_parameter "parameters" "${OPTARG}"' -p --template-parameter validate:'template_parameter_check "${OPTARG}"' var:'[{NAMESPACE_URI}]NAME=[VALUE]' -- 'テンプレートパラメータを指定する'
 	flag   parameters    --no-template-parameter init:@no on: no: -- '-p, --template-parameter をリセットする'
+	flag   skipFlag      -s --skip-error    init:@no -- 'エラーをスキップして次のファイルを処理する'
 	param  mimeType      -t --accept-type        init:='text/html,application/xhtml+xml,application/atom+xml,application/rss+xml,application/xml,text/plain,text/*,*/*' var:'MIME_TYPE[,MIME_TYPE]...' validate:"regex_match \"\${OPTARG}\" \"^(application|audio|font|example|image|message|model|multipart|text|video|x-[!#-'*+.0-9A-Z^_-z|~-]+|\*)/[!#-'*+.0-9A-Z\^_-z|~-]+(,(application|audio|font|example|image|message|model|multipart|text|video|x-[!#-'*+.0-9A-Z^_-z|~-]+|\*)/[!#-'*+.0-9A-Z\^_-z|~-]+)*$\"" -- '希望するリソースの MIME タイプを指定する'
 	disp   :usage_search -h --help               -- 'このヘルプを表示して終了する'
 }
@@ -383,7 +386,8 @@ parser_definition_show() {
 		'' 'Options:'
 
 	param  format     -f --format init:='text' pattern:'text | xml | normalized-xml' var:'text | xml | normalized-xml' -- '表示形式を指定する'
-	option indent     -s --{no-}indent-space init:@on on:2 no:0 validate:'regex_match "${OPTARG}" "^0$|^[1-9][0-9]*$"' var:'NUMBER' -- 'インデントを行う'
+	option indent     -i --{no-}indent-space init:@on on:2 no:0 validate:'regex_match "${OPTARG}" "^0$|^[1-9][0-9]*$"' var:'NUMBER' -- 'インデントを行う'
+	flag   skipFlag   -s --skip-error    init:@no -- 'エラーをスキップして次のファイルを処理する'
 	disp  :usage_show -h --help   -- 'このヘルプを表示して終了する'
 }
 
@@ -395,8 +399,9 @@ parser_definition_update() {
 		'' 'Options:'
 
 	param :'add_parameter "parameters" "${OPTARG}"' -p --template-parameter validate:'template_parameter_check "${OPTARG}"' var:'[{NAMESPACE_URI}]NAME=VALUE' -- 'テンプレートパラメータを指定する'
-	flag  parameters   --no-template-parameter init:@no on: no: -- '-p, --template-parameter をリセットする'
-	disp :usage_update -h --help  -- 'このヘルプを表示して終了する'
+	flag  parameters    --no-template-parameter init:@no on: no: -- '-p, --template-parameter をリセットする'
+	flag  skipFlag      -s --skip-error    init:@no -- 'エラーをスキップして次のファイルを処理する'
+	disp  :usage_update -h --help  -- 'このヘルプを表示して終了する'
 }
 
 parser_definition_validate() {
@@ -556,18 +561,6 @@ GETOPTIONSHERE
 }
 # Generated by getoptions (END)
 # @end
-
-argument_check() {
-	argument_to_filepath "${1}" "${2}"
-
-	eval "set -- $(eval printf '%s' "\"\${${1}}\"")"
-
-	while [ "${#}" -ne '0' ]; do
-		opensearch_file_check --err --quiet "${1}"
-
-		shift
-	done
-}
 
 argument_count_check() {
 	if [ "${1}" -lt "${2:-0}" ]; then
@@ -965,6 +958,7 @@ opensearch_contact() {
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
 extarnal='echo'
+skipFlag='0'
 REST=''
 parse_contact() {
   OPTIND=$(($#+1))
@@ -979,6 +973,10 @@ parse_contact() {
       case '--no-extarnal' in
         "$1") OPTARG=; break ;;
         $1*) OPTARG="$OPTARG --no-extarnal"
+      esac
+      case '--skip-error' in
+        "$1") OPTARG=; break ;;
+        $1*) OPTARG="$OPTARG --skip-error"
       esac
       case '--help' in
         "$1") OPTARG=; break ;;
@@ -1008,7 +1006,7 @@ parse_contact() {
       -[e]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
         ;;
-      -[h]?*) OPTARG=$1; shift
+      -[sh]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
         OPTARG= ;;
       +*) unset OPTARG ;;
@@ -1022,6 +1020,11 @@ parse_contact() {
         } || OPTARG='echo'
         extarnal="$OPTARG"
         shift ;;
+      '-s'|'--skip-error')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG='0'
+        skipFlag="$OPTARG"
+        ;;
       '-h'|'--help')
         usage_contact
         exit 0 ;;
@@ -1060,6 +1063,7 @@ Usage:
 Options:
   -e,     --{no-}extarnal[=COMMAND] 
                               外部プログラムを起動する
+  -s,     --skip-error        エラーをスキップして次のファイルを処理する
   -h,     --help              このヘルプを表示して終了する
 GETOPTIONSHERE
 }
@@ -1070,24 +1074,32 @@ GETOPTIONSHERE
 	eval "set -- ${REST}"
 
 	argument_count_check "${#}" '0' '1'
-	argument_check 'xmlFiles' "${1-}"
+	argument_to_filepath 'xmlFiles' "${1-}"
 
 	eval "set -- ${xmlFiles}"
 
 	for xmlFile in ${@+"${@}"}; do
+		opensearch_file_check --err --quiet "${xmlFile}" || skip_error "${skipFlag}" 'status' "${EX_DATAERR}"
+
 		if email="$(opensearch_select --value-of 'normalize-space(os:Contact)' "${xmlFile}")"; then :; else
 			printf "'%s' に連絡先が存在しません。\\n" "${xmlFile}" >&2
 
-			end_call "${EX_DATAERR}"
+			skip_error "${skipFlag}" 'status' "${EX_DATAERR}"
 		fi
 
 		append_array_posix 'emails' "${email}"
 	done
 
+	case "${emails-}" in
+		'') end_call "${status:-0}"
+	esac
+
 	case "${extarnal}" in
 		'echo') eval 'printf "%s\\n"' "${emails}";;
 		*) LC_ALL="${ORIGINAL_LC_ALL}" eval 'sh -c "${extarnal:-${MAILER:-mutt}} \${@+\"\${@}\"}" sh' "${emails}";;
 	esac
+
+	end_call "${status:-0}"
 }
 
 opensearch_file_check() {
@@ -1999,9 +2011,7 @@ GETOPTIONSHERE
 	for xmlFile in ${@+"${@}"}; do
 		name="${xmlFile}"
 
-		if opensearch_file_check --quiet "${xmlFile}"; then :; else
-			printf "'%s' は OpenSearch description document ではありません。\\n" "${xmlFile}" >&2
-
+		if opensearch_file_check --err --quiet "${xmlFile}"; then :; else
 			status="${EX_DATAERR}"
 			continue
 		fi
@@ -2157,9 +2167,8 @@ opensearch_normalize() {
 			</xsl:template>
 
 			<xsl:template match="
-				os:Url/@indexOffset | os:Url/@pageOffset
-				| os:Image/@width | os:Image/@height
-				| os:Query/@count | os:Query/@startIndex | os:Query/@startPage
+				os:Url/@indexOffset | os:Url/@pageOffset | os:Image/@width | os:Image/@height
+				| os:Query/@totalResults | os:Query/@count | os:Query/@startIndex | os:Query/@startPage
 			">
 				<xsl:attribute name="{name()}">
 					<xsl:value-of select="translate(normalize-space(), '+', '')"/>
@@ -2167,10 +2176,8 @@ opensearch_normalize() {
 			</xsl:template>
 
 			<xsl:template match="
-				os:Url/@template | os:Url/@type | os:Url/@rel | os:Url/@indexOffset | os:Url/@pageOffset
-				| os:Query/@role | os:Query/@totalResults | os:Query/@startIndex| os:Query/@startPage
-				| os:Query/@language | os:Query/@inputEncoding | os:Query/@outputEncoding
-				| os:Image/@width | os:Image/@height | os:Image/@type
+				os:Url/@template | os:Url/@type | os:Url/@rel | os:Image/@type
+				| os:Query/@role | os:Query/@language | os:Query/@inputEncoding | os:Query/@outputEncoding
 			">
 				<xsl:attribute name="{name()}">
 					<xsl:value-of select="normalize-space()"/>
@@ -2205,6 +2212,7 @@ opensearch_search() {
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
 extarnal='echo'
 parameters=''
+skipFlag='0'
 mimeType='text/html,application/xhtml+xml,application/atom+xml,application/rss+xml,application/xml,text/plain,text/*,*/*'
 REST=''
 parse_search() {
@@ -2228,6 +2236,10 @@ parse_search() {
       case '--no-template-parameter' in
         "$1") OPTARG=; break ;;
         $1*) OPTARG="$OPTARG --no-template-parameter"
+      esac
+      case '--skip-error' in
+        "$1") OPTARG=; break ;;
+        $1*) OPTARG="$OPTARG --skip-error"
       esac
       case '--accept-type' in
         "$1") OPTARG=; break ;;
@@ -2261,7 +2273,7 @@ parse_search() {
       -[ept]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
         ;;
-      -[h]?*) OPTARG=$1; shift
+      -[sh]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
         OPTARG= ;;
       +*) unset OPTARG ;;
@@ -2285,6 +2297,11 @@ parse_search() {
         [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
         eval '[ ${OPTARG+x} ] &&:' && OPTARG='' || OPTARG=''
         parameters="$OPTARG"
+        ;;
+      '-s'|'--skip-error')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG='0'
+        skipFlag="$OPTARG"
         ;;
       '-t'|'--accept-type')
         [ $# -le 1 ] && set "required" "$1" && break
@@ -2334,6 +2351,7 @@ Options:
                               テンプレートパラメータを指定する
           --no-template-parameter 
                               -p, --template-parameter をリセットする
+  -s,     --skip-error        エラーをスキップして次のファイルを処理する
   -t,     --accept-type MIME_TYPE[,MIME_TYPE]... 
                               希望するリソースの MIME タイプを指定する
   -h,     --help              このヘルプを表示して終了する
@@ -2345,9 +2363,9 @@ GETOPTIONSHERE
 	parse_search ${@+"${@}"}
 	eval "set -- ${REST}"
 
-	argument_count_check "${#}" '1'
-	argument_check 'xmlFiles' ${@+"${@}"}
-	shift
+	argument_count_check "${#}" '0'
+	argument_to_filepath 'xmlFiles' "${1-}"
+	shift || :
 
 	argCount="${#}"
 
@@ -2356,6 +2374,8 @@ GETOPTIONSHERE
 	eval "set -- ${xmlFiles}"
 
 	for xmlFile in  ${@+"${@}"}; do
+		opensearch_file_check --err --quiet "${xmlFile}" || skip_error "${skipFlag}" 'status' "${EX_DATAERR}"
+
 		if [ "${argCount}" -eq '0' ] \
 			&& url=$(opensearch_normalize "${xmlFile}" | opensearch_select --value-of 'moz:SearchForm' -)
 		then :; else
@@ -2364,16 +2384,22 @@ GETOPTIONSHERE
 				| opensearch_url_element_to_tsv - 'results' \
 				| eval tsv_select_url \
 					'"${xmlFile}"' '"${mimeType}"' "${parameters}"
-			) || end_call "${?}"
+			) || skip_error "${skipFlag}" 'status' "${?}" 
 		fi
 
 		append_array_posix 'urls' "${url}"
 	done
 
+	case "${urls-}" in
+		'') end_call "${status:-0}"
+	esac
+
 	case "${extarnal}" in
 		'echo') eval 'printf "%s\\n"' "${urls}";;
 		*) LC_ALL="${ORIGINAL_LC_ALL}" eval 'sh -c "${extarnal:-${BROWSER:-lynx}} \${@+\"\${@}\"}" sh' "${urls}";;
 	esac
+
+	end_call "${status:-0}"
 }
 
 opensearch_select() {
@@ -2388,6 +2414,7 @@ opensearch_show() {
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
 format='text'
 indent='2'
+skipFlag='0'
 REST=''
 parse_show() {
   OPTIND=$(($#+1))
@@ -2406,6 +2433,10 @@ parse_show() {
       case '--no-indent-space' in
         "$1") OPTARG=; break ;;
         $1*) OPTARG="$OPTARG --no-indent-space"
+      esac
+      case '--skip-error' in
+        "$1") OPTARG=; break ;;
+        $1*) OPTARG="$OPTARG --skip-error"
       esac
       case '--help' in
         "$1") OPTARG=; break ;;
@@ -2432,10 +2463,10 @@ parse_show() {
         eval 'set -- "${OPTARG%%\=*}" "${OPTARG#*\=}"' ${1+'"$@"'}
         ;;
       --no-*|--without-*) unset OPTARG ;;
-      -[fs]?*) OPTARG=$1; shift
+      -[fi]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
         ;;
-      -[h]?*) OPTARG=$1; shift
+      -[sh]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
         OPTARG= ;;
       +*) unset OPTARG ;;
@@ -2449,7 +2480,7 @@ parse_show() {
         esac
         format="$OPTARG"
         shift ;;
-      '-s'|'--indent-space'|'--no-indent-space')
+      '-i'|'--indent-space'|'--no-indent-space')
         set -- "$1" "$@"
         [ ${OPTARG+x} ] && {
           case $1 in --no-*|--without-*) set "noarg" "${1%%\=*}"; break; esac
@@ -2458,6 +2489,11 @@ parse_show() {
         regex_match "${OPTARG}" "^0$|^[1-9][0-9]*$" || { set -- regex_match:$? "$1" regex_match "${OPTARG}" "^0$|^[1-9][0-9]*$"; break; }
         indent="$OPTARG"
         shift ;;
+      '-s'|'--skip-error')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG='0'
+        skipFlag="$OPTARG"
+        ;;
       '-h'|'--help')
         usage_show
         exit 0 ;;
@@ -2496,8 +2532,9 @@ Usage:
 Options:
   -f,     --format text | xml | normalized-xml 
                               表示形式を指定する
-  -s,     --{no-}indent-space[=NUMBER] 
+  -i,     --{no-}indent-space[=NUMBER] 
                               インデントを行う
+  -s,     --skip-error        エラーをスキップして次のファイルを処理する
   -h,     --help              このヘルプを表示して終了する
 GETOPTIONSHERE
 }
@@ -2507,9 +2544,9 @@ GETOPTIONSHERE
 	parse_show ${@+"${@}"}
 	eval "set -- ${REST}"
 
-	argument_count_check "${#}" '1' '1'
-	argument_check 'xmlFiles' ${@+"${@}"}
-	shift
+	argument_count_check "${#}" '0'
+	argument_to_filepath 'xmlFiles' "${1-}"
+	shift || :
 
 	for element in ${@+"${@}"}; do
 		case "${element}" in
@@ -2537,6 +2574,8 @@ GETOPTIONSHERE
 	xmlFileCount="${#}"
 
 	for xmlFile in ${@+"${@}"}; do
+		opensearch_file_check --err --quiet "${xmlFile}" || skip_error "${skipFlag}" 'status' "${EX_DATAERR}"
+
 		if [ '2' -le "${xmlFileCount}" ]; then
 			printf '=== %s ===\n' "${xmlFile}"
 		fi
@@ -2562,6 +2601,8 @@ GETOPTIONSHERE
 			esac
 		done
 	done
+
+	end_call "${status:-0}"
 }
 
 opensearch_update() {
@@ -2569,6 +2610,7 @@ opensearch_update() {
 # Generated by getoptions (BEGIN)
 # URL: https://github.com/ko1nksm/getoptions (v3.3.0)
 parameters=''
+skipFlag='0'
 REST=''
 parse_update() {
   OPTIND=$(($#+1))
@@ -2583,6 +2625,10 @@ parse_update() {
       case '--no-template-parameter' in
         "$1") OPTARG=; break ;;
         $1*) OPTARG="$OPTARG --no-template-parameter"
+      esac
+      case '--skip-error' in
+        "$1") OPTARG=; break ;;
+        $1*) OPTARG="$OPTARG --skip-error"
       esac
       case '--help' in
         "$1") OPTARG=; break ;;
@@ -2612,7 +2658,7 @@ parse_update() {
       -[p]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" "${OPTARG#??}"' ${1+'"$@"'}
         ;;
-      -[h]?*) OPTARG=$1; shift
+      -[sh]?*) OPTARG=$1; shift
         eval 'set -- "${OPTARG%"${OPTARG#??}"}" -"${OPTARG#??}"' ${1+'"$@"'}
         OPTARG= ;;
       +*) unset OPTARG ;;
@@ -2628,6 +2674,11 @@ parse_update() {
         [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
         eval '[ ${OPTARG+x} ] &&:' && OPTARG='' || OPTARG=''
         parameters="$OPTARG"
+        ;;
+      '-s'|'--skip-error')
+        [ "${OPTARG:-}" ] && OPTARG=${OPTARG#*\=} && set "noarg" "$1" && break
+        eval '[ ${OPTARG+x} ] &&:' && OPTARG='1' || OPTARG='0'
+        skipFlag="$OPTARG"
         ;;
       '-h'|'--help')
         usage_update
@@ -2669,6 +2720,7 @@ Options:
                               テンプレートパラメータを指定する
           --no-template-parameter 
                               -p, --template-parameter をリセットする
+  -s,     --skip-error        エラーをスキップして次のファイルを処理する
   -h,     --help              このヘルプを表示して終了する
 GETOPTIONSHERE
 }
@@ -2678,13 +2730,16 @@ GETOPTIONSHERE
 	parse_update ${@+"${@}"}
 	eval "set -- ${REST}"
 
-	argument_count_check "${#}" '1' '1'
-	argument_check 'xmlFiles' ${@+"${@}"}
+	argument_count_check "${#}" '0' '1'
+	argument_to_filepath "${1-}"
 
 	eval "set -- ${xmlFiles}"
 
 	for xmlFile in ${@+"${@}"}; do
 		index=$((${index:-0} + 1))
+
+		opensearch_file_check --err --quiet "${xmlFile}" || skip_error "${skipFlag}" 'status' "${EX_DATAERR}"
+
 		downloadXML="${tmpDir}/download${index}.xml"
 		url=$(
 			opensearch_normalize "${xmlFile}" \
@@ -2693,9 +2748,9 @@ GETOPTIONSHERE
 				'"${xmlFile}"' \
 				'"${OPENSEARCH_MIME_TYPES}"' \
 				"${parameters}"
-		) || end_call "${?}"
+		) || skip_error "${skipFlag}" 'status' "${?}"
 
-		download "${downloadXML}" "${url}" "${OPENSEARCH_MIME_TYPES}"
+		download "${downloadXML}" "${url}" "${OPENSEARCH_MIME_TYPES}" || skip_error "${skipFlag}" 'status' "${EX_UNAVAILABLE}"
 
 		if
 			xml validate --err --quiet "${downloadXML}" \
@@ -2706,7 +2761,7 @@ GETOPTIONSHERE
 			printf "%s: %s は OpenSearch description document ではありません。\\n" "${0##*/}" "${url}" >&2
 			printf "詳細については '%s' を実行してください。\\n" "${0##*/} --help" >&2
 
-			end_call "${EX_DATAERR}"
+			skip_error "${skipFlag}" 'status' "${EX_DATAERR}"
 		fi
 	done
 
@@ -2715,8 +2770,12 @@ GETOPTIONSHERE
 	for xmlFile in ${@+"${@}"}; do
 		index=$((${index:-0} + 1))
 
-		cat -- "${tmpDir}/download${index}.xml" >"${xmlFile}"
+		if [ -f "${tmpDir}/download${index}.xml" ]; then
+			cat -- "${tmpDir}/download${index}.xml" >"${xmlFile}"
+		fi
 	done
+
+	end_call "${status:-0}"
 }
 
 opensearch_url_element_to_tsv() {
@@ -2885,6 +2944,13 @@ GETOPTIONSHERE
 	done
 
 	end_call "${status:-0}"
+}
+
+skip_error() {
+	case "${1}" in
+		'1') eval "${2}=\"\${3}\"; continue";;
+		*) end_call "${3}"
+	esac
 }
 
 tsv_select_url() {
